version: '3'
services:
  web:
    image: alpine-nginx-php7:latest
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    privileged: true
    volumes:
      - ../:/var/www/html
    links:
      - redis
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"