apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    tier: frontend
spec:
  containers:
    - name: simple-api-container
      image: liu71101/simple-api:v3
      ports:
        - containerPort: 8080
      env:
        - name: REDIS_HOST
          value: redis-service.default.svc.cluster.local