apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    tier: frontend
spec:
  containers:
    - name: simple-api-container
      image: liu71101/simple-api:latest
      ports:
        - containerPort: 8080